version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jorge
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongovolume:/data/db
    networks:
      - challenge
    ports:
      - '27017:27017'
  challenge:
    container_name: challenge
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./log:/target/log
    networks:
      - challenge
    depends_on:
      - mongo
networks:
  challenge:
    driver: bridge